# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0004_auto_20151205_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='foos.Player'),
        ),
    ]
