# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0005_auto_20151205_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='foos.Player'),
        ),
    ]
