# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0007_auto_20151205_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='is_open',
            field=models.NullBooleanField(),
        ),
    ]
