# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0002_auto_20151204_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
