# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0006_tourney_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='foos.Player'),
        ),
    ]
