# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0008_tourney_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='is_running',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='is_open',
            field=models.NullBooleanField(default=True),
        ),
    ]
